
// ALERT ACTION
export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

// SETUP USER LOGIN/REGISTER
export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

// TOGGLE SIDEBAR
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// LOGOUT USER
export const LOGOUT_USER = 'LOGOUT_USER'

// UPDATE USER
export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

// HANDLE CHANGE
export const HANDLE_CHANGE = 'HANDLE_CHANGE'

// CLEAR VALUES
export const CLEAR_VALUES = 'CLEAR_VALUES'

// CREATE USER
export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

// FETCH ALL JOBS
export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

// SET EDIT JOB
export const SET_EDIT_JOB = 'SET_EDIT_JOB'

// DELETE JOB
export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'

// EDIT JOB
export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

// FETCH STATS
export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

// CLEAR FILTERS
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

// CHANGE PAGE
export const CHANGE_PAGE = 'CHANGE_PAGE'

// GET CURRENT USER
export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'